image: node:16-alpine

stages:
- test
- build
- deploy

sast:
  stage: test

npm-build:
  stage: build
  script:
  - npm install --progress=false
  - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

trigger-cdk:
  stage: deploy
  trigger:
    project: $CDK_DOWNSTREAM_PROJECT
  rules:
  - if: $CI_COMMIT_TAG
    when: never
  - if: $CI_COMMIT_BRANCH == 'main'

include:
- template: Security/SAST.gitlab-ci.yml
