stages:
- test
- build
- deploy

sast:
  stage: test

npm-build:
  # Use Node 16 on Alpine
  image: node:16-alpine
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

trigger-cdk:
  stage: deploy
  trigger:
    project: $CDK_DOWNSTREAM_PROJECT

include:
- template: Security/SAST.gitlab-ci.yml
